### ISSUE TITLE
Adding asqlite to options for the sql features

### ISSUE THREAD

**Issue by DestructiveBeastro** [scarletcafe/jishaku#206]
## Request

The current SQL feature only supports (iirc) PostgreSQL and MySQL but I haven't seen SQLite and wondered if you were planning to implement it in the near future or if you don't want to.

**Comment by Gorialis** [comment]
I don't see why not.

**Comment by rtk-rnjn** [comment]
Any update?

**Comment by Gorialis** [comment]
#210 is merged in and while I don't really use SQLite in bots to audit it I'd appreciate it if you could let me know if it works for you (you need to install master)

**Comment by scarletcafe** [comment]
Because there are no further comments on this, and the mentioned PR is now in the release, I'm going to assume everything works.
